/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : USB.c
**     Project   : rapidradioUSB
**     Processor : MC9S08JS16CWJ
**     Component : Init_USB
**     Version   : Component 01.008, Driver 01.05, CPU db: 3.00.015
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 2015-09-19, 00:58
**     Abstract  :
**          This file implements the USB (USB) module initialization
**          according to the Peripheral Initialization Component settings, and defines
**          interrupt service routines prototypes.
**          The universal serial bus (USB) module supports full-speed (FS) USB device 
**          according to the Universal Serial Bus Specification Rev. 2.0.

**     Settings  :
**          Component name                                 : USB
**          Device                                         : USB
**          Voltage regulator                              : Enabled
**          PHY transceiver                                : Enabled
**          Endpoint 0:
**            Endpoint control                             : no
**            Receive enable                               : no
**            Transmit enable                              : no
**            Stall                                        : no
**            Handshake                                    : no
**          Endpoint 1:
**            Endpoint control                             : no
**            Receive enable                               : no
**            Transmit enable                              : no
**            Stall                                        : no
**            Handshake                                    : no
**          Endpoint 2:
**            Endpoint control                             : no
**            Receive enable                               : no
**            Transmit enable                              : no
**            Stall                                        : no
**            Handshake                                    : no
**          Endpoint 3:
**            Endpoint control                             : no
**            Receive enable                               : no
**            Transmit enable                              : no
**            Stall                                        : no
**            Handshake                                    : no
**          Endpoint 4:
**            Endpoint control                             : no
**            Receive enable                               : no
**            Transmit enable                              : no
**            Stall                                        : no
**            Handshake                                    : no
**          Endpoint 5:
**            Endpoint control                             : no
**            Receive enable                               : no
**            Transmit enable                              : no
**            Stall                                        : no
**            Handshake                                    : no
**          Endpoint 6:
**            Endpoint control                             : no
**            Receive enable                               : no
**            Transmit enable                              : no
**            Stall                                        : no
**            Handshake                                    : no
**          USBDP pin pull-up                              : Enabled
**          Interrupts
**            Stall interrupt                              : Disabled
**            Resume interrupt                             : Disabled
**            Sleep interrupt                              : Disabled
**            Token complete interrupt                     : Disabled
**            Start of frame interrupt                     : Disabled
**            USB reset interrupt                          : Disabled
**            Error interrupt                              : Disabled
**              Bit stuff Error interrupt                  : Disabled
**              Buffer Error interrupt                     : Disabled
**              Bus turnaround Error interrupt             : Disabled
**              Data field Error interrupt                 : Disabled
**              CRC16 Error interrupt                      : Disabled
**              CRC5 Error interrupt                       : Disabled
**              PID Error interrupt                        : Disabled
**          ISR name                                       : USB_ISR
**          Call Init method                               : yes
**          USB module Enable                              : yes
**     Contents  :
**         Init - void USB_Init(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE USB. */

#include "USB.h"


/*
** ###################################################################
**
**  The following interrupt service routines(s) must be implemented
**  by user in one of the modules listed below:

ISR(USB_ISR)
{
      // NOTE: The routine should include the following actions to obtain
      //       correct functionality of the hardware.

}
** ###################################################################
*/

/*
** ===================================================================
**     Method      :  USB_Init (component Init_USB)
**
**     Description :
**         This method initializes registers of the USB module
**         according to this Peripheral Initialization Component settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void USB_Init(void)
{
  /* USBCTL0: USBRESET=1,USBPU=0,USBRESMEN=0,LPRESF=0,??=0,USBVREN=0,??=0,USBPHYEN=0 */
  setReg8(USBCTL0, 0x80);               
  /* EPCTL0: ??=0,??=0,??=0,EPCTLDIS=0,EPRXEN=0,EPTXEN=0,EPSTALL=0,EPHSHK=0 */
  setReg8(EPCTL0, 0x00);                
  /* EPCTL1: ??=0,??=0,??=0,EPCTLDIS=0,EPRXEN=0,EPTXEN=0,EPSTALL=0,EPHSHK=0 */
  setReg8(EPCTL1, 0x00);                
  /* EPCTL2: ??=0,??=0,??=0,EPCTLDIS=0,EPRXEN=0,EPTXEN=0,EPSTALL=0,EPHSHK=0 */
  setReg8(EPCTL2, 0x00);                
  /* EPCTL3: ??=0,??=0,??=0,EPCTLDIS=0,EPRXEN=0,EPTXEN=0,EPSTALL=0,EPHSHK=0 */
  setReg8(EPCTL3, 0x00);                
  /* EPCTL4: ??=0,??=0,??=0,EPCTLDIS=0,EPRXEN=0,EPTXEN=0,EPSTALL=0,EPHSHK=0 */
  setReg8(EPCTL4, 0x00);                
  /* EPCTL5: ??=0,??=0,??=0,EPCTLDIS=0,EPRXEN=0,EPTXEN=0,EPSTALL=0,EPHSHK=0 */
  setReg8(EPCTL5, 0x00);                
  /* EPCTL6: ??=0,??=0,??=0,EPCTLDIS=0,EPRXEN=0,EPTXEN=0,EPSTALL=0,EPHSHK=0 */
  setReg8(EPCTL6, 0x00);                
  /* ERRENB: BTSERR=0,??=0,BUFERR=0,BTOERR=0,DFN8=0,CRC16=0,CRC5=0,PIDERR=0 */
  setReg8(ERRENB, 0x00);                
  /* INTENB: STALL=0,??=0,RESUME=0,SLEEP=0,TOKDNE=0,SOFTOK=0,ERROR=0,USBRST=0 */
  setReg8(INTENB, 0x00);                
  /* USBCTL0: USBRESET=0,USBPU=1,USBRESMEN=0,LPRESF=0,??=0,USBVREN=1,??=0,USBPHYEN=1 */
  setReg8(USBCTL0, 0x45);               
  /* CTL: ??=0,??=0,TSUSPEND=0,??=0,??=0,CRESUME=0,ODDRST=0,USBEN=1 */
  setReg8(CTL, 0x01);                   
}

/* END USB. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.09 [04.41]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
