/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Vectors.c
**     Project   : rapidradioUSB
**     Processor : MC9S08JS16CWJ
**     Version   : Component 01.000, Driver 01.38, CPU db: 3.00.015
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 2015-10-18, 22:32
**     Abstract  :
**         This component "MC9S08JS16_20" contains initialization 
**         of the CPU and provides basic methods and events for 
**         CPU core settings.
**     Settings  :
**
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


#include "Cpu.h"
#include "Led.h"
#include "SPI.h"
#include "USB.h"
#include "CSN.h"
#include "RfmIrq.h"
#include "TI1.h"
extern near void _EntryPoint(void);

void (* near const _vect[])(void) @0xFFC4 = { /* Interrupt vector table */
         Cpu_Interrupt,                /* Int.no. 29 Vrtc (at FFC4)                  Unassigned */
         Cpu_Interrupt,                /* Int.no. 28 VReserved28 (at FFC6)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 27 VReserved27 (at FFC8)           Unassigned */
         TI1_Interrupt,                /* Int.no. 26 Vmtim (at FFCA)                 Used */
         RfmIrq_Interrupt,             /* Int.no. 25 Vkeyboard (at FFCC)             Used */
         Cpu_Interrupt,                /* Int.no. 24 VReserved24 (at FFCE)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 23 VReserved23 (at FFD0)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 22 VReserved22 (at FFD2)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 21 Vscitx (at FFD4)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 20 Vscirx (at FFD6)                Unassigned */
         Cpu_Interrupt,                /* Int.no. 19 Vscierr (at FFD8)               Unassigned */
         Cpu_Interrupt,                /* Int.no. 18 VReserved18 (at FFDA)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 17 VReserved17 (at FFDC)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 16 VReserved16 (at FFDE)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 15 VReserved15 (at FFE0)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 14 VReserved14 (at FFE2)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 13 VReserved13 (at FFE4)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 12 VReserved12 (at FFE6)           Unassigned */
         Cpu_Interrupt,                /* Int.no. 11 Vtpmovf (at FFE8)               Unassigned */
         Cpu_Interrupt,                /* Int.no. 10 Vtpmch1 (at FFEA)               Unassigned */
         Cpu_Interrupt,                /* Int.no.  9 Vtpmch0 (at FFEC)               Unassigned */
         Cpu_Interrupt,                /* Int.no.  8 VReserved8 (at FFEE)            Unassigned */
         USB_ISR,                      /* Int.no.  7 Vusb (at FFF0)                  Used */
         Cpu_Interrupt,                /* Int.no.  6 VReserved6 (at FFF2)            Unassigned */
         Cpu_Interrupt,                /* Int.no.  5 Vspi (at FFF4)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  4 Vlol (at FFF6)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  3 Vlvd (at FFF8)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  2 Virq (at FFFA)                  Unassigned */
         Cpu_Interrupt,                /* Int.no.  1 Vswi (at FFFC)                  Unassigned */
         _EntryPoint                   /* Int.no.  0 Vreset (at FFFE)                Reset vector */
};
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.09 [04.41]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/

